# Generated by Django 3.2.18 on 2023-10-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='soserge', max_length=100),
            preserve_default=False,
        ),
    ]
